# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20170617_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupas',
            name='imagem',
            field=models.FileField(blank=True, upload_to='imagens_roupas'),
        ),
        migrations.AlterField(
            model_name='roupas',
            name='imagem1',
            field=models.FileField(blank=True, upload_to='imagens_roupas'),
        ),
        migrations.AlterField(
            model_name='roupas',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='roupas',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
